# Generated by Django 5.0.6 on 2024-06-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='certificate_name',
            new_name='certificate_number',
        ),
    ]
